import { z } from 'zod';

export const EstablishmentSchema = z.object({
  id: z.number(),
  business_name: z.string().nullable(),
  room_unit: z.string().nullable(),
  building: z.string().nullable(),
  no: z.string().nullable(),
  location: z.string().nullable(),
  owner: z.string().nullable(),
  telephone: z.string().nullable(),
  nature_of_business: z.string().nullable(),
  representative: z.string().nullable(),
  position: z.string().nullable(),
  date_approved: z.string().nullable(),
  date_of_last_renewal: z.string().nullable(),
  type: z.string().nullable(),
  status: z.string().nullable(),
  capitalization: z.string().nullable(),
  remarks: z.string().nullable(),
  ctc_no: z.string().nullable(),
  date_issued: z.string().nullable(),
  amount_paid: z.string().nullable(),
  clearance_fee: z.string().nullable(),
  remarks_on_print_business: z.string().nullable(),
  date_of_retirement: z.string().nullable(),
  sign_wordings: z.string().nullable(),
  size: z.string().nullable(),
  material: z.string().nullable(),
  sign_amount_paid: z.string().nullable(),
  sign_date: z.string().nullable(),
  sign_or: z.string().nullable(),
  custom_date: z.string().nullable(),
  custom_paid: z.string().nullable(),
  custom_or: z.string().nullable(),
  date_retirement_clearance: z.string().nullable(),
  personal_clearance_fee: z.string().nullable(),
  retirement_clearance: z.string().nullable(),
  docs_attachment: z.string().nullable(),
  signature: z.string().nullable(),
  created_by: z.string().nullable(),
  updated_by: z.string().nullable(),
  barangay_clearances_new: z.array(z.object({
    id: z.number(),
    applicant_name: z.string().nullable(),
    business_name: z.string().nullable(),
    location: z.string().nullable(),
    issued_date: z.string().nullable(),
    ownership: z.string().nullable(),
    record_no: z.string().nullable(),
    clearance_fee: z.string().nullable(),
    or_no: z.string().nullable(),
    remarks: z.string().nullable(),
    file_name: z.string().nullable(),
    created_at: z.string().nullable(),
    status: z.string().nullable(),
  })),
  barangay_clearances_renewal: z.array(z.object({
    id: z.number(),
    applicant_name: z.string().nullable(),
    business_name: z.string().nullable(),
    location: z.string().nullable(),
    issued_date: z.string().nullable(),
    ownership: z.string().nullable(),
    record_no: z.string().nullable(),
    clearance_fee: z.string().nullable(),
    or_no: z.string().nullable(),
    remarks: z.string().nullable(),
    file_name: z.string().nullable(),
    created_at: z.string().nullable(),
    status: z.string().nullable(),
  })),
});

export const EstablishmentParamsSchema = z.object({
  search: z.string().optional(),
  page: z.number().optional(),
});

export const EstablishmentFormDataSchema = EstablishmentSchema.omit({ id: true });

export type EstablishmentSchema = z.infer<typeof EstablishmentSchema>;
export type EstablishmentParams = z.infer<typeof EstablishmentParamsSchema>;
export type EstablishmentFormData = z.infer<typeof EstablishmentFormDataSchema>;
